import os

import torch

from utils.arm import LOG_SCALE_MAX, LOG_SCALE_MIN

FIXED_POINT_DTYPE = torch.int64

AC_MAX_VAL = 64

PATH_MU_SCALE_TABLE = f"{os.path.dirname(os.path.realpath(__file__))}/mu_scale.npy"


WEIGHT_SHIFT = 16
WEIGHT_SHIFT_MULT = 2**WEIGHT_SHIFT
WEIGHT_INV_SHIFT_MULT = 2**-WEIGHT_SHIFT

BIAS_SHIFT = WEIGHT_SHIFT
BIAS_SHIFT_MULT = 2**BIAS_SHIFT

N_FRAC_BIT_MU_SCALE = 8
FRAC_ACCURACY_MU_SCALE = 2**-N_FRAC_BIT_MU_SCALE

MU_MIN = -AC_MAX_VAL
MU_MAX = AC_MAX_VAL - FRAC_ACCURACY_MU_SCALE
N_POSSIBLE_MU = int((MU_MAX - MU_MIN) // FRAC_ACCURACY_MU_SCALE + 1)
MU_MIN_FIXED_POINT = MU_MIN << N_FRAC_BIT_MU_SCALE


N_POSSIBLE_SCALE = int((LOG_SCALE_MAX - LOG_SCALE_MIN) // FRAC_ACCURACY_MU_SCALE + 1)
LOG_SCALE_MIN_FIXED_POINT = LOG_SCALE_MIN << N_FRAC_BIT_MU_SCALE

N_FRAC_BIT_INTER_FT_CTX = 8
